### ISSUE TITLE
extracting odom from hajime walk control

### ISSUE THREAD

**Issue by jsupratman13** [citbrains/opr_ros#19]
はじめ歩行からodomをpublishする作業を行っています。

https://github.com/citbrains/opr_ros/blob/b25d14e710d07a9283f57c8da454d4a3a424bac2/hajime_walk_ros/include/calc_mv.h#L50-L61
上記から位置と角度を抽出しています。odomに速度と角速度を加えたいと考えていますが、**はじめ歩行で速度と角速度を計算はしていますか？**

**Comment by jsupratman13** [comment]
進捗です（パラメータ調整は後回し）
![output](https://user-images.githubusercontent.com/7608312/91997785-6afacf80-ed75-11ea-8310-ea64f1b848bd.gif)

**Comment by yasuohayashibara** [comment]
> 上記から位置と角度を抽出しています。odomに速度と角速度を加えたいと考えていますが、**はじめ歩行で速度と角速度を計算はしていますか？**

していないと思います．

**Comment by jsupratman13** [comment]
質問が答えられたためissueをcloseします
