### ISSUE TITLE
Build Error: cannot find the ftdi library

### ISSUE THREAD

**Issue by SatoshiShimada** [citbrains/opr_ros#7]
@jsupratman13 
READMEの手順とおりにインストールしている途中で、`catkin build opr_ros`を実行すると`/usr/bin/ld: cannot find -lftdi` のようなエラーが出ました。

opr_kondo_driverパッケージの https://github.com/citbrains/opr_ros/blob/c2f3aa87742755e6a9fbbea6d5ce3a24f0ed1cca/opr_kondo_driver/CMakeLists.txt#L24 のところだと思いますが、何か心当たりありませんか？

![Screenshot from 2020-01-01 17-21-38](https://user-images.githubusercontent.com/12107712/71639568-3b626780-2cbc-11ea-87d5-8ca581557a2b.png)

**Comment by jsupratman13** [comment]
#15 こちらで対応したためこのissueをcloseします
